[package]
name = "bi-focals"
version = "0.1.0"
authors = ["Mason Stallmo <masonstallmo@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/rs/lib.rs"

[dependencies]
wasm-bindgen = "0.2.37"
html5ever = "0.22.5"