// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var Tabs = /* module */[];

var Runtime = /* module */[];

exports.Tabs = Tabs;
exports.Runtime = Runtime;
/* No side effect */
