// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, BuckleScript and Reason!");

chrome.tabs.onActivated.addListener((function (active_info) {
        console.log(active_info);
        console.log(active_info.tabId);
        console.log(active_info.windowId);
        var scriptDetails = {
          code: "chrome.runtime.sendMessage({content: document.body.innerHTML}, function(response) { console.log('success'); });"
        };
        chrome.tabs.executeScript(active_info.tabId, scriptDetails, (function (param) {
                console.log("Done!");
                return /* () */0;
              }));
        return /* () */0;
      }));

chrome.runtime.onMessage.addListener((function (request, _sender, _sendResponse) {
        console.log("got the message!");
        console.log(request.content);
        return /* () */0;
      }));

/*  Not a pure module */
