// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE


console.log("Hello, BuckleScript and Reason!");

chrome.tabs.onActivated.addListener((function (active_info) {
        console.log(active_info);
        console.log(active_info.tabId);
        console.log(active_info.windowId);
        var scriptDetails = {
          code: undefined,
          file: "contentScript.js"
        };
        chrome.tabs.executeScript(active_info.tabId, scriptDetails, (function (param) {
                console.log("Done!");
                return /* () */0;
              }));
        return /* () */0;
      }));

export {
  
}
/*  Not a pure module */
