// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as Bi_focals from "../pkg/bi_focals";
import * as Tfjs from "@tensorflow/tfjs";

console.log("Hello, BuckleScript and Reason!");

chrome.tabs.onActivated.addListener((function (active_info) {
        console.log(active_info);
        console.log(active_info.tabId);
        console.log(active_info.windowId);
        var scriptDetails = {
          code: "chrome.runtime.sendMessage({content: document.body.innerHTML}, function(response) { console.log(response); });"
        };
        chrome.tabs.executeScript(active_info.tabId, scriptDetails, (function (param) {
                console.log("Done!");
                return /* () */0;
              }));
        return /* () */0;
      }));

chrome.runtime.onMessage.addListener((function (request, _sender, sendResponse) {
        console.log("got the message!");
        console.log(request.content);
        var imageSource = Bi_focals.parse_html(request.content);
        var image = new Image();
        image.src = imageSource;
        image.onload((function (param) {
                console.log("Image loaded!");
                var inputTensor = Tfjs.browser.fromPixels(image);
                console.log(inputTensor);
                return /* () */0;
              }));
        console.log(image);
        return sendResponse(imageSource);
      }));

export {
  
}
/*  Not a pure module */
